name: Build and Commit to Canary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permission to the contents scope

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Commit and push to canary branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b canary
        git add -f frontend/dist
        git commit -m "Update canary with latest build from main"
        git push origin canary --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
